package com.model;

/**
 * TLiuyan generated by MyEclipse Persistence Tools
 */

public class TLiuyan implements java.io.Serializable
{

	private Integer liuyanId;
	private String liuyanContent;
	private String liuyanDate;
	private String liuyanUser;
	
	private Integer banjiId;
	
	
	public Integer getLiuyanId()
	{
		return liuyanId;
	}
	public void setLiuyanId(Integer liuyanId)
	{
		this.liuyanId = liuyanId;
	}
	public String getLiuyanContent()
	{
		return liuyanContent;
	}
	public void setLiuyanContent(String liuyanContent)
	{
		this.liuyanContent = liuyanContent;
	}
	public String getLiuyanDate()
	{
		return liuyanDate;
	}
	public void setLiuyanDate(String liuyanDate)
	{
		this.liuyanDate = liuyanDate;
	}
	public String getLiuyanUser()
	{
		return liuyanUser;
	}
	public void setLiuyanUser(String liuyanUser)
	{
		this.liuyanUser = liuyanUser;
	}
	public Integer getBanjiId()
	{
		return banjiId;
	}
	public void setBanjiId(Integer banjiId)
	{
		this.banjiId = banjiId;
	}

}