package com.model;

/**
 * TUser generated by MyEclipse Persistence Tools
 */

public class TUser implements java.io.Serializable
{

	private Integer id;
	private String xuehao;
	private String xingming;
	private String xingbie;

	private String nianling;
	private String loginname;
	private String loginpw;
	private String xiandizhi;
	
	private String xiandanwei;
	private String xiandianhua;
	private String del;

	

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public String getXuehao()
	{
		return this.xuehao;
	}

	public void setXuehao(String xuehao)
	{
		this.xuehao = xuehao;
	}

	public String getXingming()
	{
		return this.xingming;
	}

	public String getXiandizhi() {
		return xiandizhi;
	}

	public void setXiandizhi(String xiandizhi) {
		this.xiandizhi = xiandizhi;
	}

	public String getXiandanwei() {
		return xiandanwei;
	}

	public void setXiandanwei(String xiandanwei) {
		this.xiandanwei = xiandanwei;
	}

	public String getXiandianhua() {
		return xiandianhua;
	}

	public void setXiandianhua(String xiandianhua) {
		this.xiandianhua = xiandianhua;
	}

	public void setXingming(String xingming)
	{
		this.xingming = xingming;
	}

	public String getXingbie()
	{
		return this.xingbie;
	}

	public void setXingbie(String xingbie)
	{
		this.xingbie = xingbie;
	}

	public String getNianling()
	{
		return this.nianling;
	}

	public void setNianling(String nianling)
	{
		this.nianling = nianling;
	}

	
	public String getLoginname()
	{
		return loginname;
	}

	public void setLoginname(String loginname)
	{
		this.loginname = loginname;
	}

	public String getLoginpw()
	{
		return this.loginpw;
	}

	public void setLoginpw(String loginpw)
	{
		this.loginpw = loginpw;
	}

	public String getDel()
	{
		return this.del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

}