package com.model;

/**
 * TYuanxiao generated by MyEclipse Persistence Tools
 */

public class TYuanxiao implements java.io.Serializable
{

	private Integer id;
	private String chinaProvince;
	private String chinaCity;
	private String mingcheng;
	
	private String del;

	public Integer getId()
	{
		return id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public String getChinaProvince()
	{
		return chinaProvince;
	}

	public void setChinaProvince(String chinaProvince)
	{
		this.chinaProvince = chinaProvince;
	}

	public String getChinaCity()
	{
		return chinaCity;
	}

	public void setChinaCity(String chinaCity)
	{
		this.chinaCity = chinaCity;
	}

	public String getMingcheng()
	{
		return mingcheng;
	}

	public void setMingcheng(String mingcheng)
	{
		this.mingcheng = mingcheng;
	}

	public String getDel()
	{
		return del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}
	
}