package com.model;

/**
 * TZhaopian generated by MyEclipse Persistence Tools
 */

public class TZhaopian implements java.io.Serializable
{

	private Integer id;
	private String title;
	private String fujian;
	private String shijian;
	
	private String shangchuanzhe;
	private int banjiId;
	
	
	public Integer getId()
	{
		return id;
	}
	public void setId(Integer id)
	{
		this.id = id;
	}
	public String getTitle()
	{
		return title;
	}
	public void setTitle(String title)
	{
		this.title = title;
	}
	public String getFujian()
	{
		return fujian;
	}
	public void setFujian(String fujian)
	{
		this.fujian = fujian;
	}
	public String getShijian()
	{
		return shijian;
	}
	public void setShijian(String shijian)
	{
		this.shijian = shijian;
	}
	public String getShangchuanzhe()
	{
		return shangchuanzhe;
	}
	public void setShangchuanzhe(String shangchuanzhe)
	{
		this.shangchuanzhe = shangchuanzhe;
	}
	public int getBanjiId()
	{
		return banjiId;
	}
	public void setBanjiId(int banjiId)
	{
		this.banjiId = banjiId;
	}

}